Support Scala 2.13
remove JavaConversions

Run spotlessJavaApply

    Upgrade BigQuery library

Use gradle.properties to store the scala version

Covert integration test to 2.13 and 2.12

Keep spark 3.2 in scala 2.12

Upgrade to spark 3.2 and scala 2.12-2.13 the shared project

Use the databricks-dbutils-scala that support 2.12 and 2.13

Use dynamic scala snowflake library and upgrade iceberg-spark-runtime

Upgrade project spark3 from 3.1 to 3.2

Use the databricks-dbutils-scala and iceberg-spark-runtime to support scala 2.13

Upgrade iceberg-spark-runtime to uniform to the others projects

Remove get scala versions

Remove scala-collection-compat that is not necessary

Remove reflection in ScalaConversionUtils that is not necessary

Rename to keep consistent with the name already used

Restore org.scala-lang.modules:scala-collection-compat library

Fix

Fix

Fix JdbcColumnLineageInputCollectorTest test

Signed-off-by: Mattia Bertorello <mattia.bertorello@booking.com>

Fix JdbcColumnLineageExpressionCollectorTest, JdbcColumnLineageInputCollectorTest

Signed-off-by: Mattia Bertorello <mattia.bertorello@booking.com>

Fix java.lang.NoSuchMethodError issues

Signed-off-by: Mattia Bertorello <mattia.bertorello@booking.com>

Split spark 3.1 code from the spark3 project

Signed-off-by: Mattia Bertorello <mattia.bertorello@booking.com>